const books = [
    {
        title: "Book Title 1",
        author: "Author 1",
        isbn: "1234567890",
        publisher: "Publisher 1",
        publicationDate: "2023-01-01",
        genre: "Genre 1",
        numberOfPages: 100,
        language: "English",
        description: "Description 1"
    },
    {
        title: "Book Title 2",
        author: "Author 2",
        isbn: "1234567891",
        publisher: "Publisher 2",
        publicationDate: "2023-02-01",
        genre: "Genre 2",
        numberOfPages: 200,
        language: "English",
        description: "Description 2"
    },
    {
        title: "Book Title 3",
        author: "Author 3",
        isbn: "1234567892",
        publisher: "Publisher 3",
        publicationDate: "2023-03-01",
        genre: "Genre 3",
        numberOfPages: 300,
        language: "English",
        description: "Description 3"
    },
    {
        title: "Book Title 4",
        author: "Author 4",
        isbn: "1234567893",
        publisher: "Publisher 4",
        publicationDate: "2023-04-01",
        genre: "Genre 4",
        numberOfPages: 400,
        language: "English",
        description: "Description 4"
    },
    {
        title: "Book Title 5",
        author: "Author 5",
        isbn: "1234567894",
        publisher: "Publisher 5",
        publicationDate: "2023-05-01",
        genre: "Genre 5",
        numberOfPages: 500,
        language: "English",
        description: "Description 5"
    },
    {
        title: "Book Title 6",
        author: "Author 6",
        isbn: "1234567895",
        publisher: "Publisher 6",
        publicationDate: "2023-06-01",
        genre: "Genre 6",
        numberOfPages: 600,
        language: "English",
        description: "Description 6"
    },
    {
        title: "Book Title 7",
        author: "Author 7",
        isbn: "1234567896",
        publisher: "Publisher 7",
        publicationDate: "2023-07-01",
        genre: "Genre 7",
        numberOfPages: 700,
        language: "English",
        description: "Description 7"
    },
    {
        title: "Book Title 8",
        author: "Author 8",
        isbn: "1234567897",
        publisher: "Publisher 8",
        publicationDate: "2023-08-01",
        genre: "Genre 8",
        numberOfPages: 800,
        language: "English",
        description: "Description 8"
    },
    {
        title: "Book Title 9",
        author: "Author 9",
        isbn: "1234567898",
        publisher: "Publisher 9",
        publicationDate: "2023-09-01",
        genre: "Genre 9",
        numberOfPages: 900,
        language: "English",
        description: "Description 9"
    },
    {
        title: "Book Title 10",
        author: "Author 10",
        isbn: "1234567899",
        publisher: "Publisher 10",
        publicationDate: "2023-10-01",
        genre: "Genre 10",
        numberOfPages: 1000,
        language: "English",
        description: "Description 10"
    }
];

const courses = [
    {
        courseName: "Course 1",
        courseCode: "CSE101",
        instructor: "Instructor 1",
        duration: 10,
        startDate: "2023-01-01",
        endDate: "2023-01-10",
        credits: 3,
        description: "Description 1"
    },
    {
        courseName: "Course 2",
        courseCode: "CSE102",
        instructor: "Instructor 2",
        duration: 20,
        startDate: "2023-02-01",
        endDate: "2023-02-20",
        credits: 4,
        description: "Description 2"
    },
    {
        courseName: "Course 3",
        courseCode: "CSE103",
        instructor: "Instructor 3",
        duration: 30,
        startDate: "2023-03-01",
        endDate: "2023-03-30",
        credits: 5,
        description: "Description 3"
    },
    {
        courseName: "Course 4",
        courseCode: "CSE104",
        instructor: "Instructor 4",
        duration: 40,
        startDate: "2023-04-01",
        endDate: "2023-04-40",
        credits: 6,
        description: "Description 4"
    },
    {
        courseName: "Course 5",
        courseCode: "CSE105",
        instructor: "Instructor 5",
        duration: 50,
        startDate: "2023-05-01",
        endDate: "2023-05-50",
        credits: 7,
        description: "Description 5"
    },
    {
        courseName: "Course 6",
        courseCode: "CSE106",
        instructor: "Instructor 6",
        duration: 60,
        startDate: "2023-06-01",
        endDate: "2023-06-60",
        credits: 8,
        description: "Description 6"
    },
    {
        courseName: "Course 7",
        courseCode: "CSE107",
        instructor: "Instructor 7",
        duration: 70,
        startDate: "2023-07-01",
        endDate: "2023-07-70",
        credits: 9,
        description: "Description 7"
    },
    {
        courseName: "Course 8",
        courseCode: "CSE108",
        instructor: "Instructor 8",
        duration: 80,
        startDate: "2023-08-01",
        endDate: "2023-08-80",
        credits: 10,
        description: "Description 8"
    },
    {
        courseName: "Course 9",
        courseCode: "CSE109",
        instructor: "Instructor 9",
        duration: 90,
        startDate: "2023-09-01",
        endDate: "2023-09-90",
        credits: 11,
        description: "Description 9"
    },
    {
        courseName: "Course 10",
        courseCode: "CSE110",
        instructor: "Instructor 10",
        duration: 100,
        startDate: "2023-10-01",
        endDate: "2023-10-100",
        credits: 12,
        description: "Description 10"
    }
];

const students = [
    {
      firstName: "John",
      lastName: "Doe",
      studentId: "12345",
      emailId: "john.doe@example.com",
      phoneNumber: "123-456-7890",
      dateOfBirth: "1990-01-15",
      gpa: 3.8,
      enrollmentDate: "2020-09-01",
      major: "Computer Science",
      address: "123 Main St, Anytown",
      courses: ["CS101", "CS201", "CS301"],
      certificates: ["Certification A", "Certification B"],
      libraryStatus: "Active",
      books: ["Book 1", "Book 2"],
      offerLetters: ["Offer Letter 1", "Offer Letter 2"],
      admitCard: "Admit Card 1",
      idCardStatus: "Issued" 
    },
    {
      firstName: "Jane",
      lastName: "Smith",
      studentId: "56789",
      emailId: "jane.smith@example.com",
      phoneNumber: "987-654-3210",
      dateOfBirth: "1991-05-20",
      gpa: 3.5,
      enrollmentDate: "2021-01-15",
      major: "Business Administration",
      address: "456 Elm St, Anytown",
      courses: ["BA101", "BA201", "BA301"],
      certificates: ["Certification C"],
      libraryStatus: "Active",
      books: ["Book 3", "Book 4"],
      offerLetters: ["Offer Letter 3"],
      admitCard: "Admit Card 2",
      idCardStatus: "Issued" 
    },
    {
      firstName: "David",
      lastName: "Lee",
      studentId: "101112",
      emailId: "david.lee@example.com",
      phoneNumber: "555-123-4567",
      dateOfBirth: "1992-12-10",
      gpa: 3.2,
      enrollmentDate: "2022-03-01",
      major: "Engineering",
      address: "789 Oak St, Anytown",
      courses: ["EN101", "EN201"],
      certificates: [],
      libraryStatus: "Active",
      books: ["Book 5"],
      offerLetters: [],
      admitCard: "Admit Card 3",
      idCardStatus: "Issued" 
    },
    { 
      firstName: "Sarah",
      lastName: "Jones",
      studentId: "131415",
      emailId: "sarah.jones@example.com",
      phoneNumber: "111-222-3333",
      dateOfBirth: "1993-08-25",
      gpa: 3.9,
      enrollmentDate: "2020-09-01",
      major: "Computer Science",
      address: "101 Pine St, Anytown",
      courses: ["CS101", "CS201", "CS301", "CS401"],
      certificates: ["Certification A", "Certification D"],
      libraryStatus: "Active",
      books: ["Book 6", "Book 7", "Book 8"],
      offerLetters: ["Offer Letter 4"],
      admitCard: "Admit Card 4",
      idCardStatus: "Issued" 
    },
    {
      firstName: "Michael",
      lastName: "Brown",
      studentId: "161718",
      emailId: "michael.brown@example.com",
      phoneNumber: "444-555-6666",
      dateOfBirth: "1994-02-10",
      gpa: 3.7,
      enrollmentDate: "2021-01-15",
      major: "Business Administration",
      address: "201 Maple St, Anytown",
      courses: ["BA101", "BA201", "BA302"],
      certificates: ["Certification E"],
      libraryStatus: "Active",
      books: ["Book 9"],
      offerLetters: ["Offer Letter 5", "Offer Letter 6"],
      admitCard: "Admit Card 5",
      idCardStatus: "Issued" 
    },
    {
      firstName: "Emily",
      lastName: "Davis",
      studentId: "192021",
      emailId: "emily.davis@example.com",
      phoneNumber: "777-888-9999",
      dateOfBirth: "1995-06-28",
      gpa: 3.3,
      enrollmentDate: "2022-03-01",
      major: "Engineering",
      address: "301 Oak Ave, Anytown",
      courses: ["EN101", "EN202"],
      certificates: [],
      libraryStatus: "Active",
      books: ["Book 10", "Book 11"],
      offerLetters: [],
      admitCard: "Admit Card 6",
      idCardStatus: "Issued" 
    },
    {
      firstName: "Daniel",
      lastName: "Wilson",
      studentId: "222324",
      emailId: "daniel.wilson@example.com",
      phoneNumber: "333-444-5555",
      dateOfBirth: "1996-11-12",
      gpa: 3.85,
      enrollmentDate: "2020-09-01",
      major: "Computer Science",
      address: "401 Pine Ave, Anytown",
      courses: ["CS101", "CS201", "CS301", "CS402"],
      certificates: ["Certification A", "Certification F"],
      libraryStatus: "Active",
      books: ["Book 12"],
      offerLetters: ["Offer Letter 7"],
      admitCard: "Admit Card 7",
      idCardStatus: "Issued" 
    },
    {
      firstName: "Olivia",
      lastName: "Martinez",
      studentId: "252627",
      emailId: "olivia.martinez@example.com",
      phoneNumber: "222-111-0000",
      dateOfBirth: "1997-04-05",
      gpa: 3.6,
      enrollmentDate: "2021-01-15",
      major: "Business Administration",
      address: "501 Maple Ave, Anytown",
      courses: ["BA101", "BA202", "BA303"],
      certificates: ["Certification G"],
      libraryStatus: "Active",
      books: ["Book 13", "Book 14"],
      offerLetters: ["Offer Letter 8"],
      admitCard: "Admit Card 8",
      idCardStatus: "Issued" 
    },
    {
      firstName: "James",
      lastName: "Rodriguez",
      studentId: "282930",
      emailId: "james.rodriguez@example.com",
      phoneNumber: "555-999-8888",
      dateOfBirth: "1998-07-20",
      gpa: 3.4,
      enrollmentDate: "2022-03-01",
      major: "Engineering",
      address: "601 Oak Ave, Anytown",
      courses: ["EN102", "EN203"],
      certificates: [],
      libraryStatus: "Active",
      books: ["Book 15"],
      offerLetters: [],
      admitCard: "Admit Card 9",
      idCardStatus: "Issued" 
    },
];


export { books, courses, students };